"use client";

import Image from "next/image";
import Link from "next/link";
import { FileImage, ImagePlus, LoaderCircle, Search, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { DesignLibraryItem } from "@/lib/design/types";

export type ImportedWorkspaceAsset = { id: string; name: string; path: string; thumbPath: string | null; url: string | null; thumbUrl: string | null; mimeType: string; width: number; height: number; createdAt: string; target: "source" | "clipart" };

export function WorkspaceLibraryImporter({ projectId, onImported }: { projectId: string; onImported: (asset: ImportedWorkspaceAsset) => Promise<void> }) {
  const [open, setOpen] = useState(false); const [items, setItems] = useState<DesignLibraryItem[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { if (!open || items.length) return; setLoading(true); fetch("/api/design-library?limit=100").then(async (response) => { const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "Unable to load workspace assets."); setItems(payload.items ?? []); }).catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load workspace assets.")).finally(() => setLoading(false)); }, [items.length, open]);
  const filtered = useMemo(() => items.filter((item) => !query.trim() || `${item.title} ${item.tags.join(" ")} ${item.ownerEmail}`.toLowerCase().includes(query.trim().toLowerCase())), [items, query]);
  async function importItem(item: DesignLibraryItem, target: "source" | "clipart") { setBusy(`${item.id}:${target}`); setMessage(null); const assetId = crypto.randomUUID(); try { const response = await fetch(`/api/projects/${projectId}/library-imports`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ itemId: item.id, target, assetId }) }); const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.asset) throw new Error(payload.message || "Unable to import workspace asset."); await onImported(payload.asset as ImportedWorkspaceAsset); setMessage(`${item.title} added as ${target}.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to import workspace asset."); } finally { setBusy(null); } }
  return <><button type="button" className="grid h-8 w-8 place-items-center rounded text-[var(--editor-text-dim)] hover:bg-[var(--editor-control-hover-bg)]" onClick={() => setOpen(true)} title="Import from Design workspace" aria-label="Import from Design workspace"><Sparkles size={16} /></button>{open ? <div className="workspace-library-backdrop" role="presentation"><section className="workspace-library-dialog" role="dialog" aria-modal="true" aria-labelledby="workspace-library-title"><header><div><p>Shared assets</p><h2 id="workspace-library-title">Design workspace library</h2></div><Link href="/design" target="_blank">Open Design</Link><button type="button" onClick={() => setOpen(false)} aria-label="Close workspace library"><X size={18} /></button></header><label className="workspace-library-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search designs, cliparts, tags, or owners" /></label>{message ? <p className="workspace-library-message" role="status">{message}</p> : null}<div className="workspace-library-grid">{loading ? <div className="workspace-library-loading"><LoaderCircle size={20} className="animate-spin" /> Loading shared assets…</div> : filtered.map((item) => <article key={item.id}><div className="workspace-library-preview">{item.thumbUrl || item.url ? <Image src={item.thumbUrl || item.url!} alt="" fill unoptimized sizes="180px" /> : <FileImage size={28} />}</div><div><strong>{item.title}</strong><small>{item.kind} · {item.width} × {item.height}</small></div><footer>{item.kind === "design" ? <button type="button" disabled={Boolean(busy)} onClick={() => importItem(item, "source")}>{busy === `${item.id}:source` ? <LoaderCircle size={14} className="animate-spin" /> : <ImagePlus size={14} />} Source</button> : null}<button type="button" disabled={Boolean(busy)} onClick={() => importItem(item, "clipart")}>{busy === `${item.id}:clipart` ? <LoaderCircle size={14} className="animate-spin" /> : <Sparkles size={14} />} Clipart</button></footer></article>)}</div></section></div> : null}</>;
}
