"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlignCenter, AlignHorizontalSpaceAround, ArrowDown, ArrowLeft, ArrowUp, Blend, BoxSelect, Check, ChevronDown, Circle, Copy, Crop, Download, Eraser, Eye, EyeOff, FileImage, FlipHorizontal2, FlipVertical2, Group as GroupIcon, ImagePlus, Layers3, LayoutTemplate, LoaderCircle, Lock, MousePointer2, Move, Palette, PenLine, Redo2, RotateCw, Save, Scissors, Shapes, Slash, Sparkles, Square, Trash2, Type, Undo2, Ungroup, Unlock, WandSparkles } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { removeBackgroundImageData } from "@/lib/canvas/background-removal";
import { MAX_CANVAS_DIMENSION, MAX_CANVAS_PIXELS } from "@/lib/canvas/performance-limits";
import { detectPreviewPolicy } from "@/lib/canvas/preview-policy";
import { placementForSplitRect, splitPixelRect, type DesignSplitMode } from "@/lib/design/geometry";
import { canvasToBlob, loadDesignImage, normalizeDesignFile, publishDesignBlob, renderDesignImageBitmap, uploadDesignFiles } from "@/lib/design/image-client";
import { readDesignRecoveryDraft, saveDesignRecoveryDraft } from "@/lib/design/recovery";
import { MAX_DESIGN_POINTS } from "@/lib/design/schema";
import { pruneDesignHistory } from "@/lib/design/history";
import { createBaseDesignNode, createDesignImageNode } from "@/lib/design/defaults";
import type { ExtractionCandidate } from "@/lib/design/extraction";
import type { Design, DesignDocumentV1, DesignFile, DesignImageNode, DesignMaskOperation, DesignNode, DesignPathNode, DesignShapeNode, DesignTextNode } from "@/lib/design/types";
import { DesignCanvasStage, type DesignStageHandle, type DesignTool } from "@/components/design/design-canvas-stage";
import { DesignCropDialog } from "@/components/design/design-crop-dialog";
import { ExtractionReviewDialog } from "@/components/design/extraction-review-dialog";

const HISTORY_LIMIT = 80;
const AUTOSAVE_INTERVAL_MS = 2 * 60 * 1000;
const AUTOSAVE_RETRY_MS = 3000;
const TOOL_ITEMS: Array<{ id: DesignTool; label: string; icon: typeof MousePointer2; mobile?: boolean }> = [
  { id: "select", label: "Select", icon: MousePointer2, mobile: true }, { id: "pan", label: "Pan", icon: Move, mobile: true }, { id: "draw", label: "Pencil", icon: PenLine }, { id: "marker", label: "Marker", icon: Slash }, { id: "erase", label: "Erase", icon: Eraser, mobile: true }, { id: "restore", label: "Restore", icon: WandSparkles }, { id: "lasso-erase", label: "Lasso erase", icon: BoxSelect }, { id: "lasso-restore", label: "Lasso restore", icon: Sparkles },
];

function cloneNode(node: DesignNode): DesignNode { return { ...structuredClone(node), id: crypto.randomUUID(), name: `${node.name.replace(/ copy$/i, "")} copy`, x: node.x + 24, y: node.y + 24, parentId: null }; }
function selectedBounds(nodes: DesignNode[]) { const left = Math.min(...nodes.map((node) => node.x)); const top = Math.min(...nodes.map((node) => node.y)); const right = Math.max(...nodes.map((node) => node.x + node.width)); const bottom = Math.max(...nodes.map((node) => node.y + node.height)); return { x: left, y: top, width: right - left, height: bottom - top }; }
function fileForNode(node: DesignImageNode | undefined, files: DesignFile[]) { return node ? files.find((file) => file.id === node.fileId) : undefined; }
function composeCrop(oldCrop: DesignImageNode["crop"], relative: DesignImageNode["crop"]) { return { x: oldCrop.x + relative.x * oldCrop.width, y: oldCrop.y + relative.y * oldCrop.height, width: relative.width * oldCrop.width, height: relative.height * oldCrop.height }; }
function remapMasks(masks: DesignMaskOperation[], oldCrop: DesignImageNode["crop"], nextCrop: DesignImageNode["crop"]) { const rx = (nextCrop.x - oldCrop.x) / oldCrop.width; const ry = (nextCrop.y - oldCrop.y) / oldCrop.height; const rw = nextCrop.width / oldCrop.width; const rh = nextCrop.height / oldCrop.height; const clampPoint = (value: number) => Math.max(-4, Math.min(5, value)); return masks.map((mask) => ({ ...mask, ...(mask.kind === "brush" ? { radius: Math.max(0.001, Math.min(0.5, mask.radius / Math.max(rw, 0.0001))) } : {}), points: mask.points.map((point) => ({ x: clampPoint((point.x - rx) / Math.max(rw, 0.0001)), y: clampPoint((point.y - ry) / Math.max(rh, 0.0001)) })) })) as DesignMaskOperation[]; }
function imageDataFromLike(value: { data: Uint8Array | Uint8ClampedArray; width: number; height: number }) { const pixels = new Uint8ClampedArray(value.data.length); pixels.set(value.data); return new ImageData(pixels, value.width, value.height); }

export function DesignEditorClient({ design, sessionUserId }: { design: Design; sessionUserId: string }) {
  const router = useRouter(); const stageRef = useRef<DesignStageHandle | null>(null); const fileInputRef = useRef<HTMLInputElement | null>(null); const downloadMenuRef = useRef<HTMLDetailsElement | null>(null); const pastRef = useRef<DesignDocumentV1[]>([]); const futureRef = useRef<DesignDocumentV1[]>([]); const clipboardRef = useRef<DesignNode[]>([]); const documentRef = useRef(design.document); const titleRef = useRef(design.title); const revisionRef = useRef(design.revision); const saveInFlightRef = useRef(false); const saveQueuedRef = useRef(false); const autosaveDueAtRef = useRef<number | null>(null); const geometryBakeRef = useRef(false); const lastBakedSourceRef = useRef<DesignDocumentV1 | null>(null); const historyByteBudgetRef = useRef(detectPreviewPolicy().historyBytes);
  const [document, setDocument] = useState(design.document); const [files, setFiles] = useState(design.files); const [title, setTitle] = useState(design.title); const [revision, setRevision] = useState(design.revision); const [dirty, setDirty] = useState(false); const [saveState, setSaveState] = useState<"saved" | "pending" | "saving" | "offline" | "error" | "conflict">("saved"); const [saveRetry, setSaveRetry] = useState(0); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const conflictRef = useRef(false);
  const [selectedIds, setSelectedIds] = useState<string[]>(() => design.document.nodes.filter((node) => node.type !== "group" && node.visible).slice(-1).map((node) => node.id)); const [tool, setTool] = useState<DesignTool>("select"); const [snapEnabled, setSnapEnabled] = useState(true); const [brushRadius, setBrushRadius] = useState(0.035); const [drawColor, setDrawColor] = useState("#111111"); const [drawWidth, setDrawWidth] = useState(8); const [cropOpen, setCropOpen] = useState(false); const [extractionSource, setExtractionSource] = useState<HTMLCanvasElement | null>(null);
  documentRef.current = document; titleRef.current = title;
  const selectedNodes = useMemo(() => document.nodes.filter((node) => selectedIds.includes(node.id)), [document.nodes, selectedIds]); const primaryNode = selectedNodes.at(-1); const selectedImage = primaryNode?.type === "image" ? primaryNode : undefined; const selectedFile = fileForNode(selectedImage, files);

  const markDirtyForAutosave = useCallback(() => { setDirty(true); if (conflictRef.current) { setSaveState("conflict"); return; } if (autosaveDueAtRef.current === null) autosaveDueAtRef.current = Date.now() + AUTOSAVE_INTERVAL_MS; setSaveState(navigator.onLine ? "pending" : "offline"); }, []);
  const commit = useCallback((updater: (current: DesignDocumentV1) => DesignDocumentV1) => { const current = documentRef.current; const next = updater(current); if (next === current) return; pastRef.current = pruneDesignHistory([...pastRef.current, current], HISTORY_LIMIT, historyByteBudgetRef.current); futureRef.current = []; documentRef.current = next; setDocument(next); markDirtyForAutosave(); }, [markDirtyForAutosave]);
  const changeNode = useCallback((id: string, changes: Partial<DesignNode>) => commit((current) => ({ ...current, nodes: current.nodes.map((node) => node.id === id ? { ...node, ...changes } as DesignNode : node) })), [commit]);
  const addPath = useCallback((node: DesignPathNode) => commit((current) => ({ ...current, nodes: [...current.nodes, node] })), [commit]);
  const addMask = useCallback((nodeId: string, operation: DesignMaskOperation) => commit((current) => ({ ...current, nodes: current.nodes.map((node) => node.id === nodeId && node.type === "image" ? { ...node, masks: [...node.masks, operation] } : node) })), [commit]);
  function selectNode(id: string | null, additive = false) { if (!id) { setSelectedIds([]); return; } const node = documentRef.current.nodes.find((item) => item.id === id); const groupedIds = node?.parentId ? documentRef.current.nodes.filter((item) => item.parentId === node.parentId).map((item) => item.id) : [id]; setSelectedIds((current) => { if (!additive) return groupedIds; const next = new Set(current); const remove = groupedIds.every((item) => next.has(item)); for (const item of groupedIds) remove ? next.delete(item) : next.add(item); return [...next]; }); }
  function undo() { const previous = pastRef.current.at(-1); if (!previous) return; futureRef.current = pruneDesignHistory([documentRef.current, ...futureRef.current], HISTORY_LIMIT, historyByteBudgetRef.current); pastRef.current = pastRef.current.slice(0, -1); documentRef.current = previous; setDocument(previous); markDirtyForAutosave(); setSelectedIds([]); }
  function redo() { const next = futureRef.current[0]; if (!next) return; pastRef.current = pruneDesignHistory([...pastRef.current, documentRef.current], HISTORY_LIMIT, historyByteBudgetRef.current); futureRef.current = futureRef.current.slice(1); documentRef.current = next; setDocument(next); markDirtyForAutosave(); setSelectedIds([]); }

  useEffect(() => { void readDesignRecoveryDraft(sessionUserId, design.id).then((draft) => { if (draft && !draft.synced && draft.revision >= design.revision) { documentRef.current = draft.document; setDocument(draft.document); if (draft.title) { titleRef.current = draft.title; setTitle(draft.title); } markDirtyForAutosave(); setNotice("Recovered unsaved local Design changes."); } }).catch(() => {}); }, [design.id, design.revision, markDirtyForAutosave, sessionUserId]);
  useEffect(() => { if (!dirty) return; const timer = window.setTimeout(() => { void saveDesignRecoveryDraft({ version: 1, userId: sessionUserId, designId: design.id, revision, title, document, savedAt: new Date().toISOString(), synced: false }).catch(() => {}); }, 250); return () => window.clearTimeout(timer); }, [design.id, dirty, document, revision, sessionUserId, title]);
  useEffect(() => { if (!dirty || conflictRef.current) { if (!dirty) autosaveDueAtRef.current = null; return; } if (autosaveDueAtRef.current === null) autosaveDueAtRef.current = Date.now() + AUTOSAVE_INTERVAL_MS; const delay = Math.max(0, autosaveDueAtRef.current - Date.now()); const timer = window.setTimeout(async () => {
    if (!navigator.onLine) { setSaveState("offline"); return; }
    if (saveInFlightRef.current) { saveQueuedRef.current = true; return; }
    saveInFlightRef.current = true; autosaveDueAtRef.current = null;
    const snapshot = documentRef.current; const titleSnapshot = titleRef.current; const baseRevision = revisionRef.current;
    setSaveState("saving");
    try {
      const response = await fetch(`/api/designs/${design.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ baseRevision, title: titleSnapshot, document: snapshot }) });
      const payload = await response.json().catch(() => ({}));
      if (response.status === 409) { conflictRef.current = true; saveQueuedRef.current = false; setSaveState("conflict"); return; }
      if (!response.ok) throw new Error(payload.message || "Unable to autosave Design.");
      const nextRevision = Number(payload.revision); revisionRef.current = nextRevision; setRevision(nextRevision);
      const isCurrent = documentRef.current === snapshot && titleRef.current === titleSnapshot;
      if (isCurrent) {
        setDirty(false); setSaveState("saved");
        void saveDesignRecoveryDraft({ version: 1, userId: sessionUserId, designId: design.id, revision: nextRevision, title: titleSnapshot, document: snapshot, savedAt: new Date().toISOString(), synced: true }).catch(() => {});
      } else {
        if (autosaveDueAtRef.current === null) autosaveDueAtRef.current = Date.now() + AUTOSAVE_INTERVAL_MS;
        saveQueuedRef.current = true; setSaveState(navigator.onLine ? "pending" : "offline");
      }
    } catch {
      if (!navigator.onLine) { autosaveDueAtRef.current = Date.now(); setSaveState("offline"); return; }
      autosaveDueAtRef.current = Date.now() + AUTOSAVE_RETRY_MS; setSaveState("error"); saveQueuedRef.current = true;
    } finally {
      saveInFlightRef.current = false;
      if (saveQueuedRef.current && !conflictRef.current) { saveQueuedRef.current = false; window.setTimeout(() => setSaveRetry((value) => value + 1), 0); }
    }
  }, delay); return () => window.clearTimeout(timer); }, [design.id, dirty, saveRetry, sessionUserId]);
  useEffect(() => { const online = () => { if (dirty && !conflictRef.current) { setSaveState("pending"); setSaveRetry((value) => value + 1); } }; const offline = () => { if (dirty) setSaveState("offline"); }; window.addEventListener("online", online); window.addEventListener("offline", offline); return () => { window.removeEventListener("online", online); window.removeEventListener("offline", offline); }; }, [dirty]);
  useEffect(() => {
    const pointCount = document.nodes.reduce((total, node) => total + (node.type === "image" ? node.masks.reduce((sum, mask) => sum + mask.points.length, 0) : node.type === "shape" || node.type === "path" ? node.points.length : 0), 0);
    if (pointCount < MAX_DESIGN_POINTS * 0.9 || geometryBakeRef.current || lastBakedSourceRef.current === document) return;
    geometryBakeRef.current = true; const snapshot = document;
    void (async () => {
      setBusy("bake");
      try {
        for (let attempt = 0; attempt < 20 && !stageRef.current?.isReady(); attempt += 1) await new Promise((resolve) => window.setTimeout(resolve, 100));
        if (!stageRef.current?.isReady()) throw new Error("Image layers are still rendering; geometry will be baked after they settle.");
        const canvas = stageRef.current.exportFull(); const blob = await canvasToBlob(canvas); const id = crypto.randomUUID();
        const [uploaded] = await uploadDesignFiles(design.id, [{ metadata: { id, name: `${title} flattened.png`, type: "image/png", size: blob.size, width: canvas.width, height: canvas.height }, blob }]);
        if (documentRef.current !== snapshot) { await fetch(`/api/designs/${design.id}/files`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ paths: [uploaded.path] }) }).catch(() => {}); return; }
        const flattened = createDesignImageNode({ fileId: uploaded.id, name: "Flattened artwork", width: canvas.width, height: canvas.height });
        lastBakedSourceRef.current = snapshot; setFiles((current) => [...current, uploaded]); commit((current) => current === snapshot ? { ...current, canvas: { ...current.canvas, background: null }, nodes: [flattened] } : current); setSelectedIds([flattened.id]); setNotice("Complex masks and paths were baked into an immutable image layer to keep the Design responsive.");
      } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to bake complex geometry."); }
      finally { geometryBakeRef.current = false; setBusy(null); }
    })();
  }, [commit, design.id, document, title]);
  useEffect(() => { function keydown(event: KeyboardEvent) { const target = event.target as HTMLElement | null; if (target?.matches("input, textarea, select, [contenteditable=true]")) return; const command = event.ctrlKey || event.metaKey; if (command && event.key.toLowerCase() === "z") { event.preventDefault(); event.shiftKey ? redo() : undo(); } else if (command && event.key.toLowerCase() === "y") { event.preventDefault(); redo(); } else if (command && event.key.toLowerCase() === "d") { event.preventDefault(); duplicateSelection(); } else if (command && event.key.toLowerCase() === "c") { clipboardRef.current = selectedNodes.map((node) => structuredClone(node)); } else if (command && event.key.toLowerCase() === "v") { event.preventDefault(); pasteClipboard(); } else if (event.key === "Delete" || event.key === "Backspace") deleteSelection(); } window.addEventListener("keydown", keydown); return () => window.removeEventListener("keydown", keydown); });

  function deleteSelection() { if (!selectedIds.length) return; const selected = new Set(selectedIds); commit((current) => ({ ...current, nodes: current.nodes.filter((node) => !selected.has(node.id) && !(node.type === "group" && node.childIds.every((id) => selected.has(id)))).map((node) => node.type === "group" ? { ...node, childIds: node.childIds.filter((id) => !selected.has(id)) } : node) })); setSelectedIds([]); }
  function duplicateSelection() { if (!selectedNodes.length) return; const copies = selectedNodes.filter((node) => node.type !== "group").map(cloneNode); commit((current) => ({ ...current, nodes: [...current.nodes, ...copies] })); setSelectedIds(copies.map((node) => node.id)); }
  function pasteClipboard() { if (!clipboardRef.current.length) return; const copies = clipboardRef.current.filter((node) => node.type !== "group").map(cloneNode); commit((current) => ({ ...current, nodes: [...current.nodes, ...copies] })); setSelectedIds(copies.map((node) => node.id)); }
  function reorder(id: string, direction: -1 | 1) { commit((current) => { const index = current.nodes.findIndex((node) => node.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= current.nodes.length) return current; const nodes = [...current.nodes]; [nodes[index], nodes[target]] = [nodes[target], nodes[index]]; return { ...current, nodes }; }); }
  function groupSelection() { const children = selectedNodes.filter((node) => node.type !== "group"); if (children.length < 2) { setNotice("Select at least two layers to group."); return; } const bounds = selectedBounds(children); const group = { ...createBaseDesignNode(`Group ${document.nodes.filter((node) => node.type === "group").length + 1}`, bounds.width, bounds.height, bounds.x, bounds.y), type: "group" as const, childIds: children.map((node) => node.id) }; const groupedIds = new Set(group.childIds); commit((current) => ({ ...current, nodes: [...current.nodes.filter((node) => node.type !== "group" || node.childIds.some((id) => !groupedIds.has(id))).map((node) => node.type === "group" ? { ...node, childIds: node.childIds.filter((id) => !groupedIds.has(id)) } : groupedIds.has(node.id) ? { ...node, parentId: group.id } : node), group] })); setSelectedIds(group.childIds); }
  function ungroupSelection() { const parentIds = new Set(selectedNodes.map((node) => node.parentId).filter((id): id is string => Boolean(id))); if (!parentIds.size) return; commit((current) => ({ ...current, nodes: current.nodes.filter((node) => !parentIds.has(node.id)).map((node) => parentIds.has(node.parentId || "") ? { ...node, parentId: null } : node) })); }
  function alignSelected(kind: "center" | "distribute") { if (selectedNodes.length < 2) return; if (kind === "center") { const bounds = selectedBounds(selectedNodes); commit((current) => ({ ...current, nodes: current.nodes.map((node) => selectedIds.includes(node.id) ? { ...node, x: bounds.x + (bounds.width - node.width) / 2 } : node) })); return; } const ordered = [...selectedNodes].sort((a, b) => a.x - b.x); const bounds = selectedBounds(ordered); const totalWidth = ordered.reduce((sum, node) => sum + node.width, 0); const gap = (bounds.width - totalWidth) / Math.max(1, ordered.length - 1); let x = bounds.x; const positions = new Map<string, number>(); for (const node of ordered) { positions.set(node.id, x); x += node.width + gap; } commit((current) => ({ ...current, nodes: current.nodes.map((node) => positions.has(node.id) ? { ...node, x: positions.get(node.id)! } : node) })); }
  function changeCanvas(changes: Partial<DesignDocumentV1["canvas"]>) { const canvas = { ...documentRef.current.canvas, ...changes }; if (canvas.width < 1 || canvas.height < 1 || canvas.width > MAX_CANVAS_DIMENSION || canvas.height > MAX_CANVAS_DIMENSION || canvas.width * canvas.height > MAX_CANVAS_PIXELS) { setNotice(`Canvas must stay within ${MAX_CANVAS_DIMENSION.toLocaleString()} px per axis and ${MAX_CANVAS_PIXELS.toLocaleString()} total pixels.`); return; } commit((current) => ({ ...current, canvas })); }

  function addText() { const base = createBaseDesignNode("Text", Math.min(500, document.canvas.width * 0.6), 140, document.canvas.width * 0.2, document.canvas.height * 0.4); const node: DesignTextNode = { ...base, type: "text", text: "Edit this text", fontFamily: "Geist, Arial, sans-serif", fontSize: 64, fontWeight: 600, fontStyle: "normal", align: "center", lineHeight: 1.15, letterSpacing: 0, fill: "#111111", stroke: "transparent", strokeWidth: 0, runs: [] }; commit((current) => ({ ...current, nodes: [...current.nodes, node] })); setSelectedIds([node.id]); setTool("select"); }
  function addShape(shape: DesignShapeNode["shape"]) { const width = Math.min(360, document.canvas.width * 0.4); const height = shape === "line" || shape === "arrow" ? 80 : Math.min(260, document.canvas.height * 0.3); const base = createBaseDesignNode(shape[0].toUpperCase() + shape.slice(1), width, height, (document.canvas.width - width) / 2, (document.canvas.height - height) / 2); const node: DesignShapeNode = { ...base, type: "shape", shape, points: shape === "polygon" ? [{ x: width / 2, y: 0 }, { x: width, y: height }, { x: 0, y: height }] : [], fill: shape === "line" || shape === "arrow" ? "transparent" : "#d9f3f7", stroke: "#111111", strokeWidth: 4, dash: [], cornerRadius: 12, shadowColor: "#111827", shadowBlur: 0, shadowOffsetX: 0, shadowOffsetY: 8 }; commit((current) => ({ ...current, nodes: [...current.nodes, node] })); setSelectedIds([node.id]); setTool("select"); }

  async function uploadImage(file: File) { setBusy("upload"); setNotice(null); try { const normalized = await normalizeDesignFile(file, file.name); const fileId = crypto.randomUUID(); const [uploaded] = await uploadDesignFiles(design.id, [{ metadata: { id: fileId, name: normalized.name, type: normalized.type, size: normalized.blob.size, width: normalized.width, height: normalized.height }, blob: normalized.blob }]); setFiles((current) => [...current, uploaded]); const scale = Math.min(1, document.canvas.width * 0.7 / normalized.width, document.canvas.height * 0.7 / normalized.height); const node = createDesignImageNode({ fileId, name: normalized.name, width: normalized.width * scale, height: normalized.height * scale, x: (document.canvas.width - normalized.width * scale) / 2, y: (document.canvas.height - normalized.height * scale) / 2 }); commit((current) => ({ ...current, nodes: [...current.nodes, node] })); setSelectedIds([node.id]); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to upload image."); } finally { setBusy(null); } }
  function applyCrop(nextCrop: DesignImageNode["crop"]) { if (!selectedImage) return; const aspect = nextCrop.width / nextCrop.height; const area = selectedImage.width * selectedImage.height; const width = Math.sqrt(area * aspect); const height = width / aspect; changeNode(selectedImage.id, { crop: nextCrop, masks: remapMasks(selectedImage.masks, selectedImage.crop, nextCrop), x: selectedImage.x + (selectedImage.width - width) / 2, y: selectedImage.y + (selectedImage.height - height) / 2, width, height }); setCropOpen(false); }
  function quickKeep(relative: DesignImageNode["crop"]) { if (selectedImage) applyCrop(composeCrop(selectedImage.crop, relative)); }
  async function splitSelected(mode: DesignSplitMode) { if (!selectedImage || !selectedFile?.url) return; setBusy("split"); try { const source = renderDesignImageBitmap(await loadDesignImage(selectedFile.url), selectedImage); const rects = splitPixelRect({ x: 0, y: 0, width: source.width, height: source.height }, mode); const prepared = await Promise.all(rects.map(async (rect, index) => { const canvas = window.document.createElement("canvas"); canvas.width = rect.width; canvas.height = rect.height; canvas.getContext("2d")?.drawImage(source, rect.x, rect.y, rect.width, rect.height, 0, 0, rect.width, rect.height); const blob = await canvasToBlob(canvas); return { rect, blob, metadata: { id: crypto.randomUUID(), name: `${selectedImage.name} part ${index + 1}.png`, type: "image/png" as const, size: blob.size, width: rect.width, height: rect.height } }; })); const uploaded = await uploadDesignFiles(design.id, prepared.map((item) => ({ metadata: item.metadata, blob: item.blob }))); const nodes = uploaded.map((file, index) => { const placement = placementForSplitRect(selectedImage, source, prepared[index].rect); const node = createDesignImageNode({ fileId: file.id, name: file.name, ...placement }); return { ...node, rotation: selectedImage.rotation, flipX: selectedImage.flipX, flipY: selectedImage.flipY, opacity: selectedImage.opacity, blendMode: selectedImage.blendMode, visible: selectedImage.visible, locked: selectedImage.locked, parentId: selectedImage.parentId }; }); const replacementIds = nodes.map((node) => node.id); setFiles((current) => [...current, ...uploaded]); commit((current) => ({ ...current, nodes: [...current.nodes.filter((node) => node.id !== selectedImage.id).map((node) => node.type === "group" && node.childIds.includes(selectedImage.id) ? { ...node, childIds: node.childIds.flatMap((id) => id === selectedImage.id ? replacementIds : [id]) } : node), ...nodes] })); setSelectedIds(replacementIds); setNotice(`Created ${nodes.length} independent image layers.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to split image."); } finally { setBusy(null); } }
  async function removeBackground() { if (!selectedImage || !selectedFile?.url) return; setBusy("background"); try { const source = renderDesignImageBitmap(await loadDesignImage(selectedFile.url), selectedImage); const context = source.getContext("2d", { willReadFrequently: true }); if (!context) throw new Error("Canvas is not available."); const cleaned = removeBackgroundImageData(context.getImageData(0, 0, source.width, source.height), 0.14); context.putImageData(imageDataFromLike(cleaned), 0, 0); const blob = await canvasToBlob(source); const id = crypto.randomUUID(); const [uploaded] = await uploadDesignFiles(design.id, [{ metadata: { id, name: `${selectedImage.name} transparent.png`, type: "image/png", size: blob.size, width: source.width, height: source.height }, blob }]); setFiles((current) => [...current, uploaded]); changeNode(selectedImage.id, { fileId: uploaded.id, crop: { x: 0, y: 0, width: 1, height: 1 }, masks: [] }); setNotice("Background removed. Use Restore or Erase for manual refinement."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to remove background."); } finally { setBusy(null); } }
  async function beginExtraction() { if (!selectedImage || !selectedFile?.url) return; setBusy("extract"); try { setExtractionSource(renderDesignImageBitmap(await loadDesignImage(selectedFile.url), selectedImage)); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to analyze image."); } finally { setBusy(null); } }
  async function confirmExtraction(candidates: ExtractionCandidate[], retainOriginal: boolean) {
    if (!selectedImage || !extractionSource) return;
    const uploaded: DesignFile[] = []; let committed = false; setBusy("extract"); setExtractionSource(null);
    try {
      const prepared = await Promise.all(candidates.map(async (candidate, index) => {
        const canvas = window.document.createElement("canvas"); canvas.width = candidate.width; canvas.height = candidate.height;
        const context = canvas.getContext("2d", { willReadFrequently: true }); if (!context) throw new Error("Canvas is not available.");
        context.drawImage(extractionSource, candidate.x, candidate.y, candidate.width, candidate.height, 0, 0, candidate.width, candidate.height);
        const cleaned = removeBackgroundImageData(context.getImageData(0, 0, canvas.width, canvas.height), 0.14); context.putImageData(imageDataFromLike(cleaned), 0, 0);
        const blob = await canvasToBlob(canvas); return { candidate, blob, metadata: { id: crypto.randomUUID(), name: `${selectedImage.name} clipart ${index + 1}.png`, type: "image/png" as const, size: blob.size, width: canvas.width, height: canvas.height } };
      }));
      for (let offset = 0; offset < prepared.length; offset += 24) uploaded.push(...await uploadDesignFiles(design.id, prepared.slice(offset, offset + 24).map((item) => ({ metadata: item.metadata, blob: item.blob }))));
      const nodes = uploaded.map((file, index) => { const placement = placementForSplitRect(selectedImage, extractionSource, prepared[index].candidate); const node = createDesignImageNode({ fileId: file.id, name: file.name, ...placement }); return { ...node, rotation: selectedImage.rotation, flipX: selectedImage.flipX, flipY: selectedImage.flipY, opacity: selectedImage.opacity, blendMode: selectedImage.blendMode, visible: selectedImage.visible, locked: selectedImage.locked, parentId: selectedImage.parentId }; });
      const replacementIds = nodes.map((node) => node.id);
      setFiles((current) => [...current, ...uploaded]);
      commit((current) => ({ ...current, nodes: [...current.nodes.filter((node) => retainOriginal || node.id !== selectedImage.id).map((node) => node.type === "group" && node.childIds.includes(selectedImage.id) ? { ...node, childIds: retainOriginal ? [...node.childIds, ...replacementIds] : node.childIds.flatMap((id) => id === selectedImage.id ? replacementIds : [id]) } : node), ...nodes] }));
      committed = true; setSelectedIds(replacementIds);
      let published = 0; for (let index = 0; index < prepared.length; index += 1) { await publishDesignBlob({ designId: design.id, blob: prepared[index].blob, kind: "clipart", title: prepared[index].metadata.name.replace(/\.png$/, ""), width: prepared[index].metadata.width, height: prepared[index].metadata.height }); published += 1; }
      setNotice(`${published} clipart${published === 1 ? "" : "s"} created and published.`);
    } catch (error) {
      if (!committed && uploaded.length) await fetch(`/api/designs/${design.id}/files`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ paths: uploaded.map((file) => file.path) }) }).catch(() => {});
      setNotice(error instanceof Error ? error.message : "Unable to create cliparts.");
    } finally { setBusy(null); }
  }

  async function publish(kind: "design" | "clipart") { if (!stageRef.current?.isReady()) { setNotice("Wait for all image layers to finish rendering before saving."); return; } setBusy(kind); setNotice(null); try { const canvas = kind === "design" ? stageRef.current.exportFull() : stageRef.current.exportSelection(selectedIds); if (!canvas) throw new Error("Select at least one layer to save as clipart."); const blob = await canvasToBlob(canvas); await publishDesignBlob({ designId: design.id, blob, kind, title: kind === "design" ? title : `${primaryNode?.name || title} clipart`, width: canvas.width, height: canvas.height }); setNotice(kind === "design" ? "Saved a new image to the shared Design library." : "Saved selection to the shared Clipart library."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to publish image."); } finally { setBusy(null); } }
  async function download(type: "image/png" | "image/jpeg" | "image/webp") { if (!stageRef.current?.isReady()) { setNotice("Wait for all image layers to finish rendering before downloading."); return; } setBusy("download"); setNotice(null); try { const canvas = stageRef.current.exportFull(); const blob = await canvasToBlob(canvas, type, 0.92); const url = URL.createObjectURL(blob); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = `${title.replace(/[^a-z0-9-_]+/gi, "-").replace(/^-|-$/g, "") || "design"}.${type === "image/jpeg" ? "jpg" : type.split("/")[1]}`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); downloadMenuRef.current?.removeAttribute("open"); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to download image."); } finally { setBusy(null); } }
  async function saveAsTemplate() { setBusy("template"); try { const response = await fetch(`/api/designs/${design.id}/duplicate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: `${title} template`, kind: "template", document }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || "Unable to save template."); setNotice("Saved a private editable template."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save template."); } finally { setBusy(null); } }
  async function saveConflictCopy() { setBusy("copy"); try { const response = await fetch(`/api/designs/${design.id}/duplicate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: `${title} recovered copy`, kind: "document", document }) }); const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.designId) throw new Error(payload.message || "Unable to save copy."); router.push(`/design/${payload.designId}`); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save copy."); } finally { setBusy(null); } }

  return <div className="design-editor">
    <header className="design-editor__topbar"><Link href="/design" aria-label="Back to Design workspace"><ArrowLeft size={18} /></Link><input className="design-editor__title" aria-label="Design title" value={title} maxLength={160} onChange={(event) => { titleRef.current = event.target.value; setTitle(event.target.value); markDirtyForAutosave(); }} /><span className={`design-save-state is-${saveState}`}>{saveState === "saving" ? <LoaderCircle size={14} className="animate-spin" /> : saveState === "saved" ? <Check size={14} /> : null}{saveState === "saved" ? "Saved" : saveState === "pending" ? "Unsaved" : saveState === "saving" ? "Saving…" : saveState === "offline" ? "Offline recovery" : saveState === "error" ? "Save retrying" : "Save conflict"}</span><div className="design-editor__top-actions"><button type="button" onClick={undo} disabled={!pastRef.current.length} title="Undo" aria-label="Undo"><Undo2 size={17} /></button><button type="button" onClick={redo} disabled={!futureRef.current.length} title="Redo" aria-label="Redo"><Redo2 size={17} /></button><span className="design-editor__divider" /><button type="button" onClick={saveAsTemplate} disabled={Boolean(busy)}><LayoutTemplate size={16} /><span>Template</span></button><button type="button" onClick={() => publish("clipart")} disabled={Boolean(busy) || !selectedIds.length}><Scissors size={16} /><span>Save clipart</span></button><button type="button" className="is-primary" onClick={() => publish("design")} disabled={Boolean(busy)}>{busy === "design" ? <LoaderCircle size={16} className="animate-spin" /> : <Save size={16} />}<span>Save image</span></button><details ref={downloadMenuRef} className="design-download"><summary aria-label="Download image"><Download size={16} /><ChevronDown size={13} /></summary><div><button type="button" disabled={Boolean(busy)} onClick={() => download("image/png")}>PNG</button><button type="button" disabled={Boolean(busy)} onClick={() => download("image/jpeg")}>JPEG</button><button type="button" disabled={Boolean(busy)} onClick={() => download("image/webp")}>WebP</button></div></details></div></header>
    {saveState === "conflict" ? <div className="design-conflict" role="alert"><strong>This Design changed in another session.</strong><span>Reload that version or preserve these edits as a new Design.</span><button type="button" onClick={() => window.location.reload()}>Reload</button><button type="button" onClick={saveConflictCopy}>Save as copy</button></div> : null}
    {notice ? <div className="design-editor__notice" role="status"><span>{notice}</span><button type="button" onClick={() => setNotice(null)}>×</button></div> : null}
    <div className="design-editor__workspace">
      <aside className="design-tool-rail" aria-label="Design tools">{TOOL_ITEMS.map((item) => { const Icon = item.icon; return <button type="button" key={item.id} data-mobile={item.mobile ? "true" : "false"} className={tool === item.id ? "is-active" : ""} onClick={() => setTool(item.id)} title={item.label}><Icon size={19} /><span>{item.label}</span></button>; })}<hr /><button type="button" onClick={() => fileInputRef.current?.click()} disabled={busy === "upload"} title="Add image"><ImagePlus size={19} /><span>Add image</span></button><button type="button" onClick={addText} title="Add text"><Type size={19} /><span>Text</span></button><button type="button" onClick={() => addShape("rectangle")} title="Rectangle"><Square size={19} /><span>Rectangle</span></button><button type="button" onClick={() => addShape("ellipse")} title="Ellipse"><Circle size={19} /><span>Ellipse</span></button><button type="button" onClick={() => addShape("polygon")} title="Polygon"><Shapes size={19} /><span>Polygon</span></button><button type="button" onClick={() => addShape("line")} title="Line"><Slash size={19} /><span>Line</span></button><button type="button" onClick={() => addShape("arrow")} title="Arrow"><Shapes size={19} /><span>Arrow</span></button><input ref={fileInputRef} type="file" hidden accept="image/png,image/jpeg,image/webp,image/svg+xml,application/pdf,.svg,.pdf" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadImage(file); event.currentTarget.value = ""; }} /></aside>
      <main className="design-editor__canvas"><DesignCanvasStage ref={stageRef} document={document} files={files} selectedIds={selectedIds} tool={tool} snapEnabled={snapEnabled} brushRadius={brushRadius} drawColor={drawColor} drawWidth={drawWidth} onSelect={selectNode} onChangeNode={changeNode} onAddPath={addPath} onAddMask={addMask} /></main>
      <aside className="design-inspector"><section><div className="design-inspector__heading"><Layers3 size={17} /><h2>Layers</h2><span>{document.nodes.filter((node) => node.type !== "group").length}</span></div><div className="design-layer-actions"><button type="button" onClick={groupSelection} disabled={selectedNodes.length < 2} title="Group"><GroupIcon size={15} /></button><button type="button" onClick={ungroupSelection} title="Ungroup"><Ungroup size={15} /></button><button type="button" onClick={() => alignSelected("center")} disabled={selectedNodes.length < 2} title="Align center"><AlignCenter size={15} /></button><button type="button" onClick={() => alignSelected("distribute")} disabled={selectedNodes.length < 3} title="Distribute"><AlignHorizontalSpaceAround size={15} /></button><button type="button" onClick={duplicateSelection} disabled={!selectedIds.length} title="Duplicate"><Copy size={15} /></button><button type="button" onClick={deleteSelection} disabled={!selectedIds.length} title="Delete"><Trash2 size={15} /></button></div><div className="design-layer-list">{[...document.nodes].reverse().filter((node) => node.type !== "group").map((node) => <div key={node.id} className={selectedIds.includes(node.id) ? "is-selected" : ""}><button type="button" className="design-layer-list__select" onClick={(event) => selectNode(node.id, event.shiftKey)}><span className="design-layer-list__icon">{node.type === "image" ? <FileImage size={15} /> : node.type === "text" ? <Type size={15} /> : node.type === "path" ? <PenLine size={15} /> : <Shapes size={15} />}</span><span>{node.name}</span></button><button type="button" aria-label={`${node.visible ? "Hide" : "Show"} ${node.name}`} onClick={() => changeNode(node.id, { visible: !node.visible })}>{node.visible ? <Eye size={14} /> : <EyeOff size={14} />}</button><button type="button" aria-label={`${node.locked ? "Unlock" : "Lock"} ${node.name}`} onClick={() => changeNode(node.id, { locked: !node.locked })}>{node.locked ? <Lock size={14} /> : <Unlock size={14} />}</button><button type="button" aria-label={`Move ${node.name} forward`} onClick={() => reorder(node.id, 1)}><ArrowUp size={13} /></button><button type="button" aria-label={`Move ${node.name} backward`} onClick={() => reorder(node.id, -1)}><ArrowDown size={13} /></button></div>)}</div></section>
        <section className="design-canvas-tools"><div className="design-inspector__heading"><Move size={17} /><h2>Canvas</h2></div><div className="design-field-grid"><label>Width<input type="number" min={1} max={MAX_CANVAS_DIMENSION} value={document.canvas.width} onChange={(event) => changeCanvas({ width: Math.max(1, Number(event.target.value)) })} /></label><label>Height<input type="number" min={1} max={MAX_CANVAS_DIMENSION} value={document.canvas.height} onChange={(event) => changeCanvas({ height: Math.max(1, Number(event.target.value)) })} /></label></div><label>Background<div className="design-background-field"><input type="color" value={document.canvas.background ?? "#ffffff"} onChange={(event) => changeCanvas({ background: event.target.value })} /><button type="button" className={!document.canvas.background ? "is-active" : ""} onClick={() => changeCanvas({ background: null })}>Transparent</button></div></label><button type="button" className={snapEnabled ? "design-snap-toggle is-active" : "design-snap-toggle"} onClick={() => setSnapEnabled((value) => !value)}>Snapping {snapEnabled ? "on" : "off"}</button></section>
        <section className="design-properties"><div className="design-inspector__heading"><Palette size={17} /><h2>Properties</h2></div>{primaryNode ? <><label>Name<input value={primaryNode.name} onChange={(event) => changeNode(primaryNode.id, { name: event.target.value })} /></label><div className="design-field-grid"><label>X<input type="number" value={Math.round(primaryNode.x)} onChange={(event) => changeNode(primaryNode.id, { x: Number(event.target.value) })} /></label><label>Y<input type="number" value={Math.round(primaryNode.y)} onChange={(event) => changeNode(primaryNode.id, { y: Number(event.target.value) })} /></label><label>Width<input type="number" min={1} value={Math.round(primaryNode.width)} onChange={(event) => changeNode(primaryNode.id, { width: Math.max(1, Number(event.target.value)) })} /></label><label>Height<input type="number" min={1} value={Math.round(primaryNode.height)} onChange={(event) => changeNode(primaryNode.id, { height: Math.max(1, Number(event.target.value)) })} /></label></div><label>Rotation <output>{Math.round(primaryNode.rotation)}°</output><input type="range" min={-180} max={180} value={primaryNode.rotation} onChange={(event) => changeNode(primaryNode.id, { rotation: Number(event.target.value) })} /></label><label>Opacity <output>{Math.round(primaryNode.opacity * 100)}%</output><input type="range" min={0} max={1} step={0.01} value={primaryNode.opacity} onChange={(event) => changeNode(primaryNode.id, { opacity: Number(event.target.value) })} /></label><label><Blend size={14} /> Blend mode<select value={primaryNode.blendMode} onChange={(event) => changeNode(primaryNode.id, { blendMode: event.target.value as DesignNode["blendMode"] })}><option value="normal">Normal</option><option value="multiply">Multiply</option><option value="screen">Screen</option><option value="overlay">Overlay</option><option value="darken">Darken</option><option value="lighten">Lighten</option></select></label><div className="design-transform-buttons"><button type="button" onClick={() => changeNode(primaryNode.id, { flipX: !primaryNode.flipX })}><FlipHorizontal2 size={15} /> Flip H</button><button type="button" onClick={() => changeNode(primaryNode.id, { flipY: !primaryNode.flipY })}><FlipVertical2 size={15} /> Flip V</button><button type="button" onClick={() => changeNode(primaryNode.id, { rotation: primaryNode.rotation + 90 })}><RotateCw size={15} /> 90°</button></div></> : <p className="design-inspector__empty">Select a layer to edit its properties.</p>}
          {selectedImage ? <div className="design-image-tools"><h3>Image tools</h3><div className="design-image-tools__buttons"><button type="button" onClick={() => setCropOpen(true)} disabled={!selectedFile?.url}><Crop size={15} /> Advanced crop</button><button type="button" onClick={removeBackground} disabled={Boolean(busy) || !selectedFile?.url}><WandSparkles size={15} /> Remove background</button><button type="button" onClick={beginExtraction} disabled={Boolean(busy) || !selectedFile?.url}><Scissors size={15} /> Extract cliparts</button></div><h4>Keep region</h4><div className="design-quick-grid"><button type="button" onClick={() => quickKeep({ x: 0, y: 0, width: 0.5, height: 1 })}>Left</button><button type="button" onClick={() => quickKeep({ x: 0.5, y: 0, width: 0.5, height: 1 })}>Right</button><button type="button" onClick={() => quickKeep({ x: 0, y: 0, width: 1, height: 0.5 })}>Top</button><button type="button" onClick={() => quickKeep({ x: 0, y: 0.5, width: 1, height: 0.5 })}>Bottom</button></div><h4>Split into layers</h4><div className="design-quick-grid"><button type="button" onClick={() => splitSelected("vertical")} disabled={Boolean(busy) || !selectedFile?.url}>2 vertical</button><button type="button" onClick={() => splitSelected("horizontal")} disabled={Boolean(busy) || !selectedFile?.url}>2 horizontal</button><button type="button" onClick={() => splitSelected("quarters")} disabled={Boolean(busy) || !selectedFile?.url}>4 parts</button></div><h4>Adjustments</h4>{(["brightness", "contrast", "saturation", "hue", "blur"] as const).map((key) => { const ranges = { brightness: [-1, 1, 0.01], contrast: [-100, 100, 1], saturation: [-1, 3, 0.01], hue: [-180, 180, 1], blur: [0, 30, 0.5] }[key]; return <label key={key}>{key[0].toUpperCase() + key.slice(1)} <output>{selectedImage.adjustments[key]}</output><input type="range" min={ranges[0]} max={ranges[1]} step={ranges[2]} value={selectedImage.adjustments[key]} onChange={(event) => changeNode(selectedImage.id, { adjustments: { ...selectedImage.adjustments, [key]: Number(event.target.value) } })} /></label>; })}<div className="design-adjustment-toggles">{(["grayscale", "sepia", "invert"] as const).map((key) => <button type="button" key={key} className={selectedImage.adjustments[key] ? "is-active" : ""} onClick={() => changeNode(selectedImage.id, { adjustments: { ...selectedImage.adjustments, [key]: !selectedImage.adjustments[key] } })}>{key}</button>)}</div><label>Erase brush <output>{Math.round(brushRadius * 100)}%</output><input type="range" min={0.002} max={0.2} step={0.002} value={brushRadius} onChange={(event) => setBrushRadius(Number(event.target.value))} /></label></div> : null}
          {primaryNode?.type === "text" ? <div className="design-text-tools"><h3>Text</h3><textarea value={primaryNode.text} onChange={(event) => changeNode(primaryNode.id, { text: event.target.value })} /><div className="design-field-grid"><label>Size<input type="number" min={1} value={primaryNode.fontSize} onChange={(event) => changeNode(primaryNode.id, { fontSize: Number(event.target.value) })} /></label><label>Weight<select value={primaryNode.fontWeight} onChange={(event) => changeNode(primaryNode.id, { fontWeight: Number(event.target.value) })}><option value={400}>Regular</option><option value={600}>Semibold</option><option value={700}>Bold</option></select></label></div><label>Text color<input type="color" value={primaryNode.fill} onChange={(event) => changeNode(primaryNode.id, { fill: event.target.value })} /></label></div> : null}
          {primaryNode?.type === "shape" || primaryNode?.type === "path" ? <div className="design-shape-tools"><h3>Appearance</h3><label>Stroke<input type="color" value={primaryNode.stroke} onChange={(event) => changeNode(primaryNode.id, { stroke: event.target.value })} /></label><label>Stroke width<input type="range" min={1} max={100} value={primaryNode.strokeWidth} onChange={(event) => changeNode(primaryNode.id, { strokeWidth: Number(event.target.value) })} /></label>{primaryNode.type === "shape" ? <><label>Fill<input type="color" value={primaryNode.fill === "transparent" ? "#ffffff" : primaryNode.fill} onChange={(event) => changeNode(primaryNode.id, { fill: event.target.value })} /></label><label>Line style<select value={primaryNode.dash.length ? "dashed" : "solid"} onChange={(event) => changeNode(primaryNode.id, { dash: event.target.value === "dashed" ? [16, 10] : [] })}><option value="solid">Solid</option><option value="dashed">Dashed</option></select></label><label>Shadow <output>{primaryNode.shadowBlur}px</output><input type="range" min={0} max={80} value={primaryNode.shadowBlur} onChange={(event) => changeNode(primaryNode.id, { shadowBlur: Number(event.target.value) })} /></label></> : null}</div> : null}
          {(tool === "draw" || tool === "marker") ? <div className="design-draw-tools"><h3>Drawing</h3><label>Color<input type="color" value={drawColor} onChange={(event) => setDrawColor(event.target.value)} /></label><label>Width<input type="range" min={1} max={100} value={drawWidth} onChange={(event) => setDrawWidth(Number(event.target.value))} /></label></div> : null}</section>
      </aside>
    </div>
    {cropOpen && selectedImage && selectedFile ? <DesignCropDialog node={selectedImage} file={selectedFile} onApply={applyCrop} onClose={() => setCropOpen(false)} /> : null}
    {extractionSource ? <ExtractionReviewDialog source={extractionSource} onConfirm={confirmExtraction} onClose={() => setExtractionSource(null)} /> : null}
  </div>;
}
